### ISSUE TITLE
have a 'destroy session' or 'sessionCreateFailed' method

### ISSUE THREAD

**Issue by Jonahss** [appium/appium-base-driver#12]
We need to unset the sessionID if creating a session fails, so that a new session can be created.

Drivers should surround their 'createSession' in a try/catch and undo their state. They should also call `super.destroySession` or `undoSession` or whatever we want to call it. This method should unset the sessionId.

**Comment by sebv** [comment]
Could do the try/catch in the appium package, and keep the driver simple.
