### ISSUE TITLE
/sessions populates a wrong session ID

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium-base-driver#39]
**cc** @imurchie 
#### Problem

When I do stuff with Appium (in this case Android), I can see the following types of logs:

```
info: --> POST /wd/hub/session/2993a4c6-a7c5-4403-8a21-d399e567c7f4/element/0.843447342980653-1/click {}
info: JSONWP Proxy: Proxying [POST /wd/hub/session/2993a4c6-a7c5-4403-8a21-d399e567c7f4/element/0.843447342980653-1/click] to [POST http://127.0.0.1:9515/wd/hub/session/3892423514d63a5ef6424b78a7664f10/element/0.843447342980653-1/click] with body: {}
```

Note that there are two different session IDs:
`2993a4c6-a7c5-4403-8a21-d399e567c7f4` (actual session Id)
`3892423514d63a5ef6424b78a7664f10` (session ID of the android driver)
I am not entirely sure if I have associated the session Ids right. However the problem is that when I call `GET /wd/hub/sessions` I get 

```
{ sessionId: '',
  status: 0,
  value:
   [ { capabilities: [Object],
       sessionId: '3892423514d63a5ef6424b78a7664f10' } ] }
```

It seems that the response contains the session ID from the android driver (`3892423514d63a5ef6424b78a7664f10`) which is not useful if you want to close the session.
#### Suggestion

I would replace the session Id of the android driver with the actual session Id and add another field (maybe `driverId`) to propagate the driver session Id too.

**Comment by imurchie** [comment]
Interesting. I think this is the domain of @scottdixon

**Comment by scottdixon** [comment]
@christian-bromann I'm unable to repro - can you please provide a full log gist?

**Comment by christian-bromann** [comment]
@scottdixon you can reproduce it the following way: create an Appium session (with Android capabilities) and then call `localhost:4723/wd/hub/sessions`. You should get a list with one capability which will give you an actually wrong session id.

**Comment by scottdixon** [comment]
@christian-bromann That's what I tried, here are my logs: https://gist.github.com/scottdixon/37c87793ac901ccd7be0#file-gistfile1-txt-L80-L83

Interesting to note line 78: `Replacing sessionId XXX with YYY` - do you see this in your logs?

**Comment by imurchie** [comment]
That's for proxying to ChromeDriver, @scottdixon

**Comment by scottdixon** [comment]
@imurchie I thought this might be getting skipped. @christian-bromann did you make any progress?
