### ISSUE TITLE
Don't export tests in index.js

### ISSUE THREAD

**Issue by sebv** [appium/appium-base-driver#4]
Missed that, we don't want to propagate test dependencies in non test code, the dependency are not installed when you do `npm install` in a parent.

If we need to share test we should probably move the tests to their own package.

cc @jlipps

**Comment by jlipps** [comment]
yeah i guess i didn't think it was such a big deal, there was only one testdep i had to export as a real dep to make this work.

but i'm open to there being a better way!

it's an interesting use case that i don't think NPM is set up well for.

**Comment by sebv** [comment]
You can do that:
```js
var tests = require("appium-base-driver/build/test/driver-e2e-tests");
```
or create a index.js in test, but doesn't fix the dependency issue.

**Comment by jlipps** [comment]
true, but then we could just add the dep to the devDeps of the current project

**Comment by rkavalap** [comment]
This is no longer relevant. Closing.
