### ISSUE TITLE
User prompts non spec compliant.

### ISSUE THREAD

**Issue by rafael-chavez** [appium/appium-base-driver#60]
https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L178 

should match:

https://www.w3.org/TR/webdriver/#dfn-accept-alert

Alongside dismiss alert, send alert text, and get alert text.

**Comment by rafael-chavez** [comment]
@jlipps @Jonahss ^^

**Comment by jlipps** [comment]
@rafael-chavez are we non-compliant with the existing webdriver clients? The w3c spec has not yet been adopted in most clients AFAICT

**Comment by rafael-chavez** [comment]
your correct this is only for new w3spec clients. Should we support both older webdriver and new w3c spec clients or wait until w3c spec has been further adopted?

**Comment by rafael-chavez** [comment]
Main issue @jlipps is that appium-xcuitest-driver is using a commit of WebDriverAgent they are already updated to the w3c spec.

**Comment by imurchie** [comment]
This is already updated in our xxuitest driver. It just translates the
endpoint.

**Comment by jlipps** [comment]
@rafael-chavez you're right that we need a migration strategy. TBH I haven't thought much about this. Supporting both simultaneously is the best option, however I'm not sure there aren't some endpoints which have just changed, which would mean a breaking change in Appium. We'll need to dig into this and figure out how the Selenium project is migrating, and do something similar.

**Comment by rkavalap** [comment]
Currently this issue is tracked in main appium repo #7346
