### ISSUE TITLE
Add TouchID enrollment endpoint

### ISSUE THREAD

**Issue by midopa** [appium/appium-base-driver#87]
This is an option available in the iOS simulators:
http://i.stack.imgur.com/ml3L9.png

This will allow more comprehensive testing of negative path flows for TouchID UI integration.

Something like:
```
POST /wd/hub/session/{sessionId}/appium/simulator/touch_id_enrolled/
BODY: {isEnrolled: true|false}
Set or unset simulator to TouchID enrolled state
```

**Comment by imurchie** [comment]
Is there any way to do this, on the device side?

**Comment by jlipps** [comment]
@dpgraham is working on adding touchid endpoints to the clients right now. If we are going to change this we'd better do it soon.

but if it's a device setting, sounds like "touch Id enrolled" is really more of a session capability than a parameter to the touchId endpoint itself.

**Comment by dpgraham** [comment]
http://stackoverflow.com/questions/25459059/is-there-any-way-to-use-apples-touch-id-fingerprint-scanner-on-ios-simulator

Enrolling a simulator for touch id is a setting which would be a session capability. But we may need to implement an endpoint that checks if the user is enrolled.

**Comment by dpgraham** [comment]
...although if we already control that through session capabilities, being able to check if they're enrolled wouldn't be very useful.

**Comment by rkavalap** [comment]
Closing as fixed. 
https://github.com/appium/appium/issues/7013

**Comment by midopa** [comment]
It's not clear to me if the changes in appium/appium#7013 expose the Touch ID enrollment action.
@rkavalap Can you confirm?

In iOS simulators, to use Touch ID, you need to first "enroll" in it. Then you do Touch ID match/pass. From looking at some of the PRs associated with 7013, it seems only the Appium clients were updated to add the Touch ID match/pass APIs. Not the enrollment.

**Comment by rkavalap** [comment]
@midopa Thanks for pointing that out. I will open a separate issue for this in the main appium repo to track the work.
